### ISSUE TITLE
Odoo Client Error after click "Aprove/Refuse" buttons in inspection_line_ids

### ISSUE THREAD

**Issue by rpsjr** [OCA/fleet#69]
**Environment**: Odoo v13.0 in OCA Runbot

**Steps to reproduce**: 

1. Create a new (draft) inspection;

2. Press "Aprove/Refuse" buttons without/before saving it.

**Error**:

Traceback:
TypeError: Cannot read property 'length' of undefined
    at Class._render (http://3487614-13-0-ed26f2.runbot2.odoo-community.org/web/content/519-c2770f7/web.assets_backend.js:3208:4416)
    at http://3487614-13-0-ed26f2.runbot2.odoo-community.org/web/content/519-c2770f7/web.assets_backend.js:821:1408

**Comment by marcelsavegnago** [comment]
If you can do the same test at 12 and if possible at 14 I would appreciate it.

Preferably do in version 12.0 please

**Comment by rpsjr** [comment]
> If you can do the same test at 12 and if possible at 14 I would appreciate it.
> 
> Preferably do in version 12.0 please

The problem does exist in v12.0.

Under v14 the same problem doesn't exist. But a standard Validation Error appears when the "Aprove/Refuse" buttons are used in the wizard, traceback below.

**v12.0:**

`Error:
Uncaught TypeError: Cannot read property 'length' of undefined

http://3487812-12-0-e35a0f.runbot2.odoo-community.org/web/content/671-025e294/web.assets_backend.js:2979
Traceback:
TypeError: Cannot read property 'length' of undefined
    at Class._render (http://3487812-12-0-e35a0f.runbot2.odoo-community.org/web/content/671-025e294/web.assets_backend.js:2979:3949)
    at http://3487812-12-0-e35a0f.runbot2.odoo-community.org/web/content/671-025e294/web.assets_backend.js:1051:1521
    at http://3487812-12-0-e35a0f.runbot2.odoo-community.org/web/content/665-f88aa1b/web.assets_common.js:802:681
    at fire (http://3487812-12-0-e35a0f.runbot2.odoo-community.org/web/content/665-f88aa1b/web.assets_common.js:796:299)
    at Object.add [as done] (http://3487812-12-0-e35a0f.runbot2.odoo-community.org/web/content/665-f88aa1b/web.assets_common.js:797:467)
    at Array.<anonymous> (http://3487812-12-0-e35a0f.runbot2.odoo-community.org/web/content/665-f88aa1b/web.assets_common.js:802:649)
    at Function.each (http://3487812-12-0-e35a0f.runbot2.odoo-community.org/web/content/665-f88aa1b/web.assets_common.js:625:767)
    at Object.<anonymous> (http://3487812-12-0-e35a0f.runbot2.odoo-community.org/web/content/665-f88aa1b/web.assets_common.js:802:560)
    at Function.Deferred (http://3487812-12-0-e35a0f.runbot2.odoo-community.org/web/content/665-f88aa1b/web.assets_common.js:803:194)
    at Object.then (http://3487812-12-0-e35a0f.runbot2.odoo-community.org/web/content/665-f88aa1b/web.assets_common.js:802:525)`


**v14.0 :**

The operation cannot be completed:
- Create/update: a mandatory field is not set.
- Delete: another model requires the record being deleted. If possible, archive it instead.

Model: Fleet Vehicle Inspection Line (fleet.vehicle.inspection.line), Field: Inspection Reference (inspection_id)
